# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login-GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 711)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1371, 711))
        self.label.setStyleSheet("QFrame    \n"
"{\n"
"    background:#333;\n"
"    border-radius:30px;\n"
"}\n"
"*{\n"
"   font-family:Calibri;\n"
"   font-size:55px\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("clouds.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 70, 501, 591))
        self.frame.setStyleSheet("*{\n"
"   font-family:Calibri;\n"
"   font-size:55px\n"
"}\n"
"QFrame    \n"
"{\n"
"    background:#333;\n"
"    border-radius:30px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 50, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"border-radius:none;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 141, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Calibri\";\n"
"border:transparent;\n"
"border-radius:none;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 24pt \"Calibri\";\n"
"border:transparent;\n"
"border-radius:none;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(160, 180, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"font: 22pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:none;\n"
"border-bottom:1px solid#717270")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 240, 331, 41))
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"font: 20pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:none;\n"
"border-bottom:1px solid#717270")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.loginbutton = QtWidgets.QPushButton(self.frame)
        self.loginbutton.setGeometry(QtCore.QRect(190, 360, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("color: rgb(255, 255, 0);\n"
"background:transparent;\n"
"border-radius:none;")
        self.loginbutton.setObjectName("loginbutton")
        self.exitbutton = QtWidgets.QPushButton(self.frame)
        self.exitbutton.setGeometry(QtCore.QRect(210, 450, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.exitbutton.setFont(font)
        self.exitbutton.setStyleSheet("background:transparent;\n"
"color: rgb(255, 0, 0);\n"
"border-radius:none;")
        self.exitbutton.setObjectName("exitbutton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "LOGIN FORM"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.loginbutton.setText(_translate("MainWindow", "Login"))
        self.exitbutton.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
